color: null
fieldLayouts:
  3ed04b44-cb7b-4b3a-8327-66ba3565ccb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-28T09:52:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 360e3acc-e6f8-4353-be3e-1324a3a33d1c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T10:03:34+00:00'
            elementCondition: null
            fieldUid: 438243f5-3528-40db-89f7-320c3bb39e29 # Photo
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2463eb7-db1c-4c3b-8ec9-014685cf5d4f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:55:24+00:00'
            elementCondition: null
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: credentials
            includeInCards: false
            instructions: null
            label: Credentials
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c360500-80b2-43f1-89a3-c176d2453877
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:55:24+00:00'
            elementCondition: null
            fieldUid: ace47efd-105d-41d5-8d5f-55a57c7ba41e # Overview
            handle: text
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a87f3be-5c08-4dab-bf5b-4abbb6225fd7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ebd7969-d393-4777-98d4-b16f777fbaf4
        userCondition: null
handle: brandAmbassador
hasTitleField: true
icon: ''
name: 'Brand Ambassador'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
