color: null
fieldLayouts:
  8d85c036-c02c-41a9-a240-7387077408ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-28T16:23:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Event Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 381f1d6b-459b-4c89-b8df-f2aad532fa6c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T16:27:56+00:00'
            elementCondition: null
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: location
            includeInCards: false
            instructions: null
            label: Location
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e284d10e-5a96-42b5-98f5-e8b08300fa48
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T16:27:56+00:00'
            elementCondition: null
            fieldUid: ace47efd-105d-41d5-8d5f-55a57c7ba41e # Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f9cd461-d958-4cd3-b385-c367a0d2703d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T16:27:56+00:00'
            elementCondition: null
            fieldUid: 7fd658cb-e8ae-46cd-8c3d-52af5f71352f # Start Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f37da29-ea5a-429a-8a34-a171fba8b527
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T16:27:56+00:00'
            elementCondition: null
            fieldUid: 07c2344d-19d1-4f25-a166-64c27853ab9d # Multi Day?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cba8a5bc-9cec-47d9-ab69-b73945230c33
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T16:27:56+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 07c2344d-19d1-4f25-a166-64c27853ab9d # Multi Day?
                  layoutElementUid: cba8a5bc-9cec-47d9-ab69-b73945230c33
                  uid: a97a6214-a59e-4d31-9606-3e1232cf2a3f
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7fd658cb-e8ae-46cd-8c3d-52af5f71352f # Start Date
            handle: endDate
            includeInCards: false
            instructions: null
            label: 'End Date'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2e44ef5-09aa-4583-b581-24ddf978687c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T16:27:56+00:00'
            elementCondition: null
            fieldUid: 69c03b0f-93dd-41d5-b683-4c65029a399a # Event Website
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c571fdf-cf96-454e-8059-f62a2f3cb57e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6987148-d3dc-4fd6-afec-88c6ce103eb1
        userCondition: null
handle: event
hasTitleField: true
icon: ''
name: Event
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
