color: null
fieldLayouts:
  de0bb91d-f32a-40f5-be76-4758fb307dc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-29T13:26:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Office Location'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 50a6beb9-45dd-4f14-a880-403051d147dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T13:30:35+00:00'
            elementCondition: null
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: companyName
            includeInCards: false
            instructions: null
            label: 'Company Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d7bfad1-4ecc-476a-938e-72488760c7a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T13:30:35+00:00'
            elementCondition: null
            fieldUid: 53531453-fab3-46f7-a890-f0a81a999180 # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cff8d2b-7d3b-4b7e-a974-f87aef084ba1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T13:30:35+00:00'
            elementCondition: null
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: cin
            includeInCards: false
            instructions: null
            label: CIN
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ac93add-8faf-4062-bdc5-6725e6cba285
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T13:30:35+00:00'
            elementCondition: null
            fieldUid: 1d125c5c-0a0c-4b2d-984f-01aaf91b0747 # Email Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68377302-1e91-4fe1-a6b6-63cc5797ee32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T13:30:35+00:00'
            elementCondition: null
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: contactNumber
            includeInCards: false
            instructions: null
            label: 'Contact Number'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64bd2dc2-81a2-40c9-865e-2b63a6492373
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66d6ba8a-68d5-4de7-9944-d53ae2cf6cbc
        userCondition: null
handle: location
hasTitleField: true
icon: ''
name: Location
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
