color: null
fieldLayouts:
  c40fa6b4-9963-49b1-827d-c533a4434a3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-22T14:39:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 269b325f-f7b0-41fb-946a-2cbd502f145a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T23:36:03+00:00'
            elementCondition: null
            fieldUid: d2d8e874-9460-48c8-beed-355df0e4a564 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97874c47-3ae0-484f-b09d-1c11f5da9834
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68c726f9-f8d6-49ce-8501-242143f28396
        userCondition: null
handle: standard
hasTitleField: true
icon: ''
name: Standard
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
