color: null
fieldLayouts:
  c40fa6b4-9963-49b1-827d-c533a4434a3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-22T14:39:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 269b325f-f7b0-41fb-946a-2cbd502f145a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:26:18+00:00'
            elementCondition: null
            fieldUid: ace47efd-105d-41d5-8d5f-55a57c7ba41e # Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae8b8f1f-a4f8-4b06-accf-6198ba0bd899
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:26:18+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: babc85f0-2210-4aab-9f05-c2b3774e2ada
            userCondition: null
          -
            dateAdded: '2024-08-22T23:36:03+00:00'
            elementCondition: null
            fieldUid: d2d8e874-9460-48c8-beed-355df0e4a564 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97874c47-3ae0-484f-b09d-1c11f5da9834
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:58:45+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 58c5e1ad-61ba-4f66-b55d-1ac4ccfd29ee
                  value: brand-ambassadors
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 57737f4b-6c39-496e-bd34-06936ecbce43 # Brand Ambassadors
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df035f96-b65f-4edb-b7f5-0a5b79c46863
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T13:51:44+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 2ed91a16-e361-4e1e-b087-ab2af30804d6
                  value: sponsorship
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0cdf5e66-0279-4f0a-8f0f-06c654bfc5ac # Sponsorships
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11821d50-0f35-4828-9e5a-1442308bb991
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68c726f9-f8d6-49ce-8501-242143f28396
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-28T22:37:54+00:00'
            elementCondition: null
            fieldUid: 6ba08a18-cefd-493b-be25-ba634a67d787 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a75f964-dc5d-43fa-93fa-b22692ef49be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T22:37:54+00:00'
            elementCondition: null
            fieldUid: 0cbecadd-ee18-404d-b340-501f913e1d53 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44e4760b-d015-4631-ac1a-3295dbb332cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T22:37:54+00:00'
            elementCondition: null
            fieldUid: cc21e5aa-4f58-422f-ace2-09ade4574993 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ae152d7-ba55-4893-9d70-d9d9804a1843
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 051c978e-fa8e-4b66-b2eb-8af59135eefa
        userCondition: null
handle: standard
hasTitleField: true
icon: ''
name: Standard
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
