color: null
fieldLayouts:
  c40fa6b4-9963-49b1-827d-c533a4434a3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-22T14:39:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 269b325f-f7b0-41fb-946a-2cbd502f145a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T15:18:44+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: dea9ce69-fcf2-4ee4-8ee5-e9492ce47f04
                  value: __home__
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: tagline
            includeInCards: false
            instructions: null
            label: Tagline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd780396-1ad2-4f10-93d5-7bc51e0c129c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:26:18+00:00'
            elementCondition: null
            fieldUid: ace47efd-105d-41d5-8d5f-55a57c7ba41e # Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae8b8f1f-a4f8-4b06-accf-6198ba0bd899
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:26:18+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: babc85f0-2210-4aab-9f05-c2b3774e2ada
            userCondition: null
          -
            dateAdded: '2024-08-29T14:58:24+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 3c6db875-d9fb-4b84-8e49-3a942b1ac75a
                  value: __home__
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 27ff068c-8f1b-43ee-9615-76759afe72ef # Photos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d644fd6-d3d0-43fe-b3ce-3dbef513b8e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T14:58:24+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 1ab0ddc1-bcc0-4066-b2fe-fbd8d2188bf3
                  value: __home__
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: subheading
            includeInCards: false
            instructions: null
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a990054-c4f9-4322-b65e-461b6b36ff26
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T23:36:03+00:00'
            elementCondition: null
            fieldUid: d2d8e874-9460-48c8-beed-355df0e4a564 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97874c47-3ae0-484f-b09d-1c11f5da9834
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T15:00:05+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 5a036921-db86-473a-be6a-a168e401866d
                  value: __home__
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d2d8e874-9460-48c8-beed-355df0e4a564 # Text
            handle: secondaryParagraph
            includeInCards: false
            instructions: null
            label: 'Secondary Paragraph'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823c4b85-e054-46c3-936a-955291e1556a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T14:55:54+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: c4590567-6da1-493c-9fea-8a5289b0a1ae
                  value: __home__
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 9e52894c-723b-4299-91a4-6616e96654f3 # Stats
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26b86b08-575c-4c5d-bba7-68633f3e8f98
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T09:58:45+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 58c5e1ad-61ba-4f66-b55d-1ac4ccfd29ee
                  value: brand-ambassadors
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 57737f4b-6c39-496e-bd34-06936ecbce43 # Brand Ambassadors
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df035f96-b65f-4edb-b7f5-0a5b79c46863
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T13:51:44+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 2ed91a16-e361-4e1e-b087-ab2af30804d6
                  value: sponsorship
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0cdf5e66-0279-4f0a-8f0f-06c654bfc5ac # Sponsorships
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11821d50-0f35-4828-9e5a-1442308bb991
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T13:31:41+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: f0de9e19-c96e-4300-ba5d-0fc18717552e
                  value: contact
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: cfd3bc6f-e43b-4c4c-9c57-74ab44f0804c # Locations
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7001661-ccf9-4978-b3ac-e47142ea566f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-29T15:32:17+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: '='
                  uid: 781405dc-f779-404c-9588-589755379c6c
                  value: terms
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b569a424-dcb9-4020-812d-807d38655abf # Documents
            handle: null
            includeInCards: false
            instructions: null
            label: 'Terms & Conditions Document'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f31af246-090b-4829-8d5b-a935e509f6b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68c726f9-f8d6-49ce-8501-242143f28396
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-28T22:37:54+00:00'
            elementCondition: null
            fieldUid: 6ba08a18-cefd-493b-be25-ba634a67d787 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a75f964-dc5d-43fa-93fa-b22692ef49be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T22:37:54+00:00'
            elementCondition: null
            fieldUid: 0cbecadd-ee18-404d-b340-501f913e1d53 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44e4760b-d015-4631-ac1a-3295dbb332cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-28T22:37:54+00:00'
            elementCondition: null
            fieldUid: cc21e5aa-4f58-422f-ace2-09ade4574993 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ae152d7-ba55-4893-9d70-d9d9804a1843
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 051c978e-fa8e-4b66-b2eb-8af59135eefa
        userCondition: null
handle: standard
hasTitleField: true
icon: ''
name: Standard
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
