altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c76d85c2-270f-4751-ab3b-44888ed2c083:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-22T20:29:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 703ea3f6-f753-4e2e-b3fc-5a742df33384
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T20:31:46+00:00'
            elementCondition: null
            fieldUid: f72b528d-6b33-4330-aa32-e66eaebc9164 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa69b6f-ce9d-417d-80b7-650409677e51
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T20:31:46+00:00'
            elementCondition: null
            fieldUid: ace47efd-105d-41d5-8d5f-55a57c7ba41e # Overview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd01e28b-556f-4657-899f-7b868806b5d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T20:33:22+00:00'
            elementCondition: null
            fieldUid: 955fe759-5ee7-4082-b22a-42b3712b6cd8 # Published
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b690ff7-dd42-4fab-a7fa-398de66ee19d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7752e574-1d2f-4fbc-abaf-4deb921884cf
        userCondition: null
fs: assets
handle: documents
name: Documents
sortOrder: 2
subpath: documents
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
