altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fc3d4ebe-27b3-48f4-bd51-26f6a2274394:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-22T20:29:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fdcea7be-867e-4bfa-94ec-4a5a8a830469
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4726b151-4835-4d31-91a6-117747ea535e
        userCondition: null
fs: assets
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
