columnSuffix: null
handle: emailAddress
instructions: null
name: 'Email Address'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
