columnSuffix: null
handle: multiDay
instructions: null
name: 'Multi Day?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
