defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f9de22e0-c294-424e-aace-d29a5ee22038 # Brand Ambassador
handle: brandAmbassadors
maxAuthors: 1
minAuthors: 1
name: 'Brand Ambassadors'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6c1f48e9-4588-4100-8f79-5410aacc580e: # Healthcare International Research
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
