defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a5524528-c323-41f0-9271-c50a0c48b04d # Event
handle: events
maxAuthors: 1
minAuthors: 1
name: Events
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6c1f48e9-4588-4100-8f79-5410aacc580e: # Healthcare International Research
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
