defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 778c4b04-b6ad-49b4-9178-86911f2aaee1 # Sponsorship
handle: sponsorships
maxAuthors: 1
minAuthors: 1
name: Sponsorships
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6c1f48e9-4588-4100-8f79-5410aacc580e: # Healthcare International Research
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
